### ISSUE TITLE
GI Public TODO List

### ISSUE THREAD

**Issue by StavWasPlayZ** [StavWasPlayZ/Genshin-Instruments#20]
# Stav's Genshin Instruments Public TODO List

This is a list of all things planned for the Genshin Instruments mod.

This was originally a file in my personal computer that I would constantly update and delete lines from to keep track of things I wanna do/fix within the mod.

I decided to make it public for transparency's sake - to showcase what my general plans are, show progress on some stuff, and maybe (maybe) for anyone to make some contribution on these matters? 🤔

It is (I hope) an established fact that I am a solo developer on this pretty huge project. I am also a student, volunteer, software developer, and... in possession of a life.  
This unfortunately means that things, in general, ***will*** be delayed, until I am free, ready and not burnt out to commit to work on this thing.

Feel free to chop in for some help, or add something of your own in a new issue/PR! :)

> [!NOTE]
> This list may be separated from other issues that might exist in this repository. A specific issue not appearing here ***does not*** mean I do not intend to tackle it - unless otherwise stated.

---

- [ ] 1.20.1, 1.21.1 - invalid version range (fixed?)

- [ ] Add Quartz to top right of Nightwind recipe.  
Makes more sense imo.
  - [ ] UPDATE CF & MODRINTH SCREENSHOTS

- [ ] Fix item tags not being translated:
  - [ ] Dev warning - Untranslated Item Tags detected. Please translate your item tags so other mods such as recipe viewers can properly display your tag's name.
    - The format desired is `tag.item.<namespace>.<path>` for the translation key with slashes in path turned into periods.
    - To disable this message, set this system property in your runs: `-Dfabric-tag-conventions-v2.missingTagTranslationWarning=SILENCED`.
    - To see individual untranslated item tags found, set the system property to `-Dfabric-tag-conventions-v2.missingTagTranslationWarning=VERBOSE`.
    - Default is `SHORT`.

- [ ] Fix Z-fighting in the Nightwind model (present on the center gold thing)

- [ ] Surround `GridInstrumentScreen#renderStaff` and `GridInstrumentScreen#renderClef` with `RenderSystem.enable/disableBlend()` (should solve alpha sometimes locked to 100%)

- [ ] Globally search for "RenderSystem.enable", and disable where it doesn't.

- [ ] Make `ModCapabilities#notifyOpenStateToPlayer` public (move isOpen condition to said function)

- [ ] Test genshin consent screen with Linux scaling
  - [ ] If it's fine, remove "`annoyingY`" thing.

- [ ] Check for a better way to sync capabilities/tags (open capability)
  Currently:
    - [ ] In 1.20.4+, client sends info request for each new server entity
    - [ ] Below, server sends on dimension traversal and on join
    - **LEX REPLY TO SOME RANDOM DUDE**: There is a player copy event/other events when a player switches dimensions; you need to make sure you copy your cap there.

- [ ] Make held instruments sustainable with pedal

- [ ] Fix MIDI pressing pedal then E then releasing pedal then releasing E... not releasing E

- [ ] Add option 1/3rd right to note labels type for a "fixed" toggle (boolean). Separate it and the current "fixed" options.

- [ ] Make `InstrumentScreen` generic to sound type(?)
  - [ ] Re-structure the API in general:
    - `NoteSoundType`: an empty interface (for now) dictating that the following object is a note sound type;
    - `GridInstrumentScreen` becomes a general interface;
    - `InstrumentScreen<S extends NoteSoundType>`
       - `LegatoInstrumentScreen extends InstrumentScreen<LegatoNoteSound>`
         - `LegatoGridInstrumentScreen extends LegatoInstrumentScreen implements GridInstrumentScreen`
       - `StaccatoInstrumentScreen extends InstrumentScreen<StaccatoNoteSound>`
         - `StaccatoGridInstrumentScreen extends StaccatoInstrumentScreen implements GridInstrumentScreen`
       
    
- [ ] Make all keyboard input be MIDI input for instruments.
  - [ ] Pitch slider should now be transposition.
  - [ ] Then, remove the useless 'key' parameter for all MIDI handlers (which is always 0).
  - [ ] Make option to play with keys 1-0 on higher octave.
  - [ ] Make option to switch keyboard layout (e.g., Genshin to Virtual Piano one).

- [ ] Rename mixin package name to either mixins (fabric) or mixin (forge) [parity]

- [ ] Fix `ClientEvents` block instrument arm pose applying only to player (should be all entities)

- [ ] Add MIDI file support via 3rd-party mod

## Regarding Native MIDI Player Support

Many have requested native MIDI player support for this mod.

My general attitude towards this request was always to encourage *actually* learning the instrument, but that you *can* play with some roundabout methods. I liked it this way, since the player that wanted to, quote-unquote, "cheat" - had to go some way to do this.

After a lot of requests, I came to the decision of allowing an "official" adaptation of MIDI players - a client-only ***"MIDI Player for Genshin Instruments"*** mod, that would allow for a new "Load MIDI file..." button in MIDI options and drag-and-drop behavior of MIDI files, that the mod could later play.  
This still aligns with my view that the player *should* do some kind of action to actually do this "cheating". But it doesn't require the usage of some unknown-for 3rd-party software or geeky computer knowledge. Simply an "are you sure you wanna do this?" barrier.

 At least that's how I see it.  
 Still debatable.  But I think this judgement is alright.  
 I hope it's understandable.
